### ISSUE TITLE
BUG: "Resource not accessible by integration"

### ISSUE THREAD

**Issue by moul** [z0al/dependent-issues#72]
![Screenshot - Manfred 2021-03-11 at 10 43 46](https://user-images.githubusercontent.com/94029/110767644-c3e07e80-8256-11eb-916f-37da2db4da64.png)

https://github.com/berty/berty/pull/3143/checks?check_run_id=2084969829

I regularly need to manually relaunch this failing GitHub action, can you give a look at what is happening and if possible update your script in order to not mark a PR as failed when you've internal errors? (if you don't like this default behavior, maybe you can add an option to force this behavior)

Thank you!

**Comment by z0al** [comment]
Hey @moul . Thanks for report this issue. 

I'm afraid the issue `Resource not accessible by integration` is not really related to this GitHub action. The error message basically means the given `GITHUB_TOKEN` (automatically created by GitHub) has no write access to the repo (In this case, write access is needed to update PR labels & status).

Recently, GitHub [changed the behavior of Dependabot PRs to have read-only permission](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/) to prevent security issues. That caused the behavior you're expecting for [multiple users](https://github.community/t/intermittent-resource-not-accessible-by-integration-errors/166930), including my own repos. I have other third-party actions that are now failing randomly due to the same issue.


>  if possible update your script in order to not mark a PR as failed when you've internal errors

This is not an internal error as explained above, if the action can't do what is supposed to do due to lack of permissions then it's either a misconfiguration or a GitHub buggy behavior.

**Comment by moul** [comment]
What do you think about adding an option to silently ignore this kind of error instead of marking the whole PR as failed?

In our case, it always happens in only two cases:
* When an external contributor open a PR
* when a bot open a PR (dependabot etc)

We are only using the "depends on #xxx", "blocks #xxx" on core team PRs, but never on the bot and external contributor's ones

At Berty, we try to limit as much as possible the amount of external code that can use privileged tokens, so we need a solution like this or just remove the integration completely

**Comment by z0al** [comment]
> adding an option to silently ignore this kind of error instead of marking the whole PR as failed?

I understand your frustration but let's think of that proposal for a second again. If that error occurs it means without a doubt that we have _an invalid or read-only token_. In that case, this Action **won't be able to do** the followings:

* Comment on a PR 
* Update the PR Status
* Add or remove labels

And that's pretty much what this action is about tbh so I don't think it makes sense to have an option that disables the only things the action is supposed to do.

As I said before, this is a configuration issue. The recent changes in the way GitHub actions work caused so much confusion and I'm now trying to understand what the configuration should look like for an action like this. When I find something I will be updating the README so it's clear for everyone. 

> In our case, it always happens in only two cases:
> * When an external contributor open a PR

I don't know why this case is failing as we are using `pull_request_target`. I will need to investigate. You may also want to read [this guide by GitHub](https://securitylab.github.com/research/github-actions-preventing-pwn-requests).

> * when a bot open a PR (dependabot etc)

This should also be fixable but it may also make sense for your case to completely ignore PRs created by Dependabot e.g.

```yaml
steps:
  - uses: z0al/dependent-issues@v1
    if: ${{ github.actor != 'dependabot[bot]' }} # Skip the action if the PR was created by Dependabot.
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by z0al** [comment]
One thing that can be done by the action though is to provide options for automatically ignoring dependabot PRs and _possibly_ PRs created by non-collaborators too.

**Comment by z0al** [comment]
> One thing that can be done by the action though is to provide options for automatically ignoring dependabot PRs

I just pushed this change.  Starting now, any new Dependabot PR will be ignored automatically. This behavior is not configurable, which I guess is fine.

**Comment by moul** [comment]
Ok thank you :+1:
